Dockerfile, components/Form/AppControlInput.vue, components/home/Details.vue, components/register/PhaseOne.vue, docker-compose.yaml
Update Docker file
Update docker compose
Update input field in registration form 
Update Homepage Robot image, now hasfixed sizes
=> General Code clean up and CSS fixes

components/member/Avatar.vue, components/member/Card.vue, components/member/Contribution.vue, components/member/Details.vue, components/member/Experience.vue, components/member/Score.vue, pages/members/[id].vue
Implemented Desktop design 
Fix mobile view for member profile
Add static components:
- Member contribution
- Member score
=> Member profile refactor

components/Form/AppDropDownSearch.vue, components/member/Contribution.vue, components/member/Experience.vue, components/members/PaginationBar.vue, components/register/PhaseThree.vue, pages/members/[id].vue
Some css fixes
Some design changes
Search member now  search from API
=> Refactor project

components/members/Filter.vue, components/members/index.vue
Now filteration is all managed by the Api search
=> Update members directory page

.env.sample, .gitignore, Dockerfile, components/Form/AppDropDownSearch.vue, components/members/index.vue, docker-compose.yaml, nuxt.config.ts, pages/members/[id].vue, pages/register/index.vue
add envsample 
replaced env var names with a standard convention
=> update env vars on project

components/member/Banner.vue, components/member/Card.vue, components/member/Contribution.vue, components/member/Details.vue, components/member/Score.vue, components/members/Card.vue, components/members/Filter.vue, components/members/index.vue, pages/members/[id].vue
Integrate the following pages and components with V2 of the API
- Members
- Member Directory
- Members contribution
=> Patch api v2 integration

components/mission/Card.vue, components/mission/Filter.vue, components/mission/Info.vue, components/mission/index.vue, pages/missions/index.vue
update assigned checkbox, update assigned tag
=> Fix issues with mission filters

components/Banner.vue, components/member/Banner.vue, components/member/Card.vue, components/members/Filter.vue, components/members/index.vue, components/mission/Filter.vue, pages/index.vue, pages/members/index.vue, pages/missions/index.vue, tailwind.config.js
now search member uses paginate and lists the number of found results, also, paginate has been hidden when no result is found
=> patch: General CSS and tiny functionality fixes

nuxt.config.ts, package-lock.json, package.json, volar.config.js
upgrade nuxt 3, add nuxt vite builder, add volar package, add nuxt device,
=> chore: upgrade npm packages

components/members/index.vue, components/mission/index.vue
Enabled multifilter for members and missions
=> Refactor: enable multifilter

.drone.yml
add build args for development enviroment
=> build: update drone file

components/members/Card.vue
=> Remove the target attribute from member's card

components/members/Card.vue
=> Unify paddings between Directory and Profile

components/member/Contribution.vue, components/member/Details.vue
=> fix: wrong margin under the paragraph in about

components/member/Banner.vue
=> fix: add right margin to general-info container

components/member/Banner.vue
=> fix: align location icon with the location text

components/member/Banner.vue, components/member/Contribution.vue, components/member/Experience.vue
=> fix: Enhance Typography on Profile Page (Mobile)

components/member/Contribution.vue, components/member/Experience.vue
=> feat: sort experience and education by date

components/members/Filter.vue
=> fix: filter closes when scrolling or clicking on the text field on mobile

components/member/Contribution.vue, components/member/Experience.vue
=> fix: use divider separator svg instead of slashes

components/Form/EarlyAccess.vue
=> Change the colour of the submit button in EarlyAccess component

components/member/Contribution.vue, components/member/Experience.vue
=> fix: dates now take a separate line in small screen

components/members/Filter.vue, components/members/index.vue
=> feat: autoscroll to members list when clicking on the search button

components/Form/AppControlInput.vue, components/members/Filter.vue
=> Fix: preserve the state of the filter's checkbox when collapsing the filter menu

components/Form/AppControlInput.vue, components/home/HeroBanner.vue, components/member/Banner.vue, components/member/Contribution.vue, components/member/Experience.vue, components/member/Settings.vue, components/members/Filter.vue, components/mission/Filter.vue, middleware/register.js, pages/register/index.vue
check if member has any wikimedia_edits
=> general bug fixes

components/Form/AppDropDown.vue, components/member/Details.vue, components/member/Experience.vue, components/member/PermissionDropDown.vue
section visibilty depends now on the boolean values and permission level
=> refactor: change section visibilty criteria

components/UserWidget.vue, components/login/Form.vue, components/member/Banner.vue, composables/state.js
=> User widget fixes

components/member/Contribution.vue, pages/members/[id].vue
hide show more button when there are not too many contributions
=> refactor: open source contributions

assets/css/global.css, components/member/Experience.vue, public/icons/delete.svg, tailwind.config.js
replace x icon with trash icon
=> Fix: general member profile fixes

components/MobileMenuItems.vue, components/PageHeader.vue
clicking on mobile nav items will now auto close the navbar
=> Auto close the navigation

server/api/healthcheck.get.ts
=> Feat: add a simple heathcheck endpoint
